### ISSUE TITLE
Examples aren't work

### ISSUE THREAD

**Issue by NoSocialLifeException** [fynnfluegge/oreon-engine#56]
Running OpenGL example throw this:

`INFO  [GLContext] OpenGL version: 4.3.13543 Core Profile Context 25.20.15002.58
Exception in thread "main" java.lang.NullPointerException
	at org.oreon.core.gl.util.GLAssimpModelLoader.loadModel(GLAssimpModelLoader.java:42)
	at org.oreon.gl.components.atmosphere.Atmosphere.<init>(Atmosphere.java:23)
	at org.oreon.examples.gl.oreonworlds.GLOreonworlds.main(GLOreonworlds.java:22)`

after removing line `renderEngine.getSceneGraph().addObject(new Atmosphere());` will run.
https://imgur.com/a/HTAWP61

Same situation with Vulkan example, but i dont find any solution to fix it.

`INFO  [PhysicalDevice] Available Physical Devices: 1
INFO  [QueueFamilies] Available Queues: 3
INFO  [QueueFamilies] Index:0 flags:15 count:1 presentation:1
INFO  [QueueFamilies] Index:1 flags:14 count:2 presentation:1
INFO  [QueueFamilies] Index:2 flags:12 count:2 presentation:1
INFO  [DeviceCapabilities] Device: Radeon RX 580 Series
INFO  [LogicalDevice] No compute exclusive queue available on device: Radeon RX 580 Series
INFO  [LogicalDevice] No transfer exclusive queue available on device: Radeon RX 580 Series
Could not decode image file [C:/Users/Admin/Desktop/Oreon%20Engine/oreon-engine-master/oreonengine/oe-core/target/classes/gui/tex/Fonts.png]: [Unable to open file]
Exception in thread "main" java.lang.NullPointerException
	at org.oreon.core.vk.wrapper.buffer.StagingBuffer.<init>(StagingBuffer.java:19)
	at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImage(VkImageHelper.java:74)
	at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImageFromFile(VkImageHelper.java:49)
	at org.oreon.vk.components.ui.VkGUI.init(VkGUI.java:133)
	at org.oreon.examples.vk.oreonworlds.VkSystemMonitor.init(VkSystemMonitor.java:24)
	at org.oreon.vk.engine.VkDeferredEngine.init(VkDeferredEngine.java:184)
	at org.oreon.examples.vk.oreonworlds.VkOreonworlds.main(VkOreonworlds.java:18)`

GPU: AMD Radeon RX 580 Aorus
OpenGL version: 25.20.15002.58
Vulkan version: 2.0.64

**Comment by fynnfluegge** [comment]
This cannot be, I run it on both branches, master and develop and I don't get these Nullpointerexceptions
