### ISSUE TITLE
GlOreonworlds - NullPointer Exception

### ISSUE THREAD

**Issue by CyberPaz** [fynnfluegge/oreon-engine#75]
Exception in thread "main" java.lang.NullPointerException
	at org.oreon.core.gl.util.GLAssimpModelLoader.loadModel(GLAssimpModelLoader.java:113)
	at org.oreon.gl.components.atmosphere.Atmosphere.<init>(Atmosphere.java:22)
	at org.oreon.examples.gl.oreonworlds.GLOreonworlds.main(GLOreonworlds.java:23)

Everytime I start the program. Always give me an java.lang.NullPointerException. Please someone help me and explain why happened ?

**Comment by Diamantino-Op** [comment]
I know why it happens, and i'm trying to fix it, if i'll fix it, i'll tell you how to do it

**Comment by Diamantino-Op** [comment]
Ok, i found a solution, this isn't a bug, it only works when exported to jar.
But by exporting to jar you get other problems, that i fixed with a modification of the resource loaders.
