### ISSUE TITLE
Running VkOreonWorlds swapchain crash

### ISSUE THREAD

**Issue by zakiisak** [fynnfluegge/oreon-engine#95]
Hey there!

I just cloned the repository and built the example projects. 
When running the Vulkan Oreon Worlds within the examples-vulkan project it crashes immediately when the call to the swapchain draw method is being made. Here is a stacktrace.

FYI My system uses Windows 11, with a GTX 1080 GPU.

Exception in thread "main" java.lang.AssertionError: A surface has changed in such a way that it is no longer compatible with the swapchain, and further presentation requests using the swapchain will fail. Applications must query the new surface properties and recreate their swapchain if they wish to continuepresenting to the surface.
	at org.oreon.core.vk.util.VkUtil.vkCheckResult(VkUtil.java:61)
	at org.oreon.core.vk.swapchain.SwapChain.draw(SwapChain.java:347)
	at org.oreon.vk.engine.VkDeferredEngine.render(VkDeferredEngine.java:317)
	at org.oreon.core.CoreEngine.render(CoreEngine.java:117)
	at org.oreon.core.CoreEngine.run(CoreEngine.java:91)
	at org.oreon.core.CoreEngine.start(CoreEngine.java:44)
	at org.oreon.examples.vk.oreonworlds.VkOreonworlds.main(VkOreonworlds.java:24)

**Comment by fynnfluegge** [comment]
Hey @zakiisak thanks for reporting!
Seems it is the VK_ERROR_OUT_OF_DATE_KHR error.
Guess this is an easy fix. I am on Mac currently and cannot test this. 
Any PR is welcome if you like to raise one! 🙌
